### ISSUE TITLE
app closing

### ISSUE THREAD

**Issue by Mateus017** [KuatoDev/GreenForce-Official-Apps#1]
Build version: 1.1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2022-12-29 16:27:39 
Device: Xiaomi 21061110AG 
 
Stack trace:  
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.valueOf(Integer.java:801)
	at t8.v.run(Unknown Source:39)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:676)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by KuatoDev** [comment]
Known issue. Will be fixed in future release
